version: '3.7'

services:
  db:
    # build: ./containers/mssql
    # container_name: fast_database
    # user: root
    # ports:
    #   - 1433:1433
    # volumes:
    #   - sqlserver:/var/opt/mssql/data
    image: mcr.microsoft.com/mssql/server
    container_name: fast_database
    user: root
    ports:
      - 1433:1433
    restart: on-failure
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ssw0rd!'
    volumes:
      - sqlserver:/var/opt/mssql/data
  app:
    build: .
    container_name: fast_api
    ports:
      - 8000:8000
    volumes:
      - .:/home/FastAPIStore
    links:
      - db
    depends_on:
      - db

volumes:
  sqlserver:
    driver: local
