version: '3.7'

services:
  db:
    # build: ./containers/mssql
    # container_name: fast_database
    # restart: on-failure
    # ports:
    #   - 1433:1433
    # # command: bash -c "./entrypoint.sh"
    # volumes:
    #   - type: volume
    #     source: data
    #     target: /var/opt/mssql
    image: mcr.microsoft.com/mssql/server
    container_name: fast_database
    user: root
    ports:
      - 1433:1433
    restart: on-failure
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Passw0rd'
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
  app:
    build: .
    container_name: fast_api
    ports:
      - 8000:8000
    volumes:
      - .:/home/FastAPIStore
    links:
      - db
    depends_on:
      - db

volumes:
  data:
